# Jellyfin transmuxing proxy config file.

# Server config.
# At least one of enable_http or enable_http has to be present.
[server]
  # Enable HTTP.
  enable_http = true

  # HTTP Listen port or address. Optional.
  http_listen = 8097

  # Enable HTTPS.
  #enable_https = true

  # HTTPS listen port or address. Optional.
  #https_listen = 443

  # HTTPS certificate. optional if https_listen_port is not set.
  #tls_cert = "/etc/certs/example.crt"

  # HTTPS private key. optional if https_listen_port is not set.
  #tls_key = "/etc/certs/example.key"

# Special settings for Safari.
[safari]
  # Hack for safari.
  force_transcoding = true

# Settins for the Jellyfin server we proxy to.
[jellyfin]
  # Jellyfin server.
  jellyfin = "http://127.0.0.1:8096"

  # Media root. Optional (also a command line option).
  # mediaroot = "/tmp"

# Segment caching.
[cache]
  # Cache limits
  max_memory_mb = 512
  max_segments = 100
  ttl_secs = 300

  # generate segments in advance.
  lookahead = 2
